version: "3.0"

expectations:
  population_size: 100000

actions:
  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  generate_post1stJuly_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_post1stJuly
    outputs:
      highly_sensitive:
        cohort_post1stJuly: output/input_post1stJuly.csv

  prepare_data:
    run: stata-mp:latest analysis/01_hh_cr_analysis_dataset.do
    needs: [generate_cohort, generate_post1stJuly_cohort]
    outputs:
      highly_sensitive:
        allvars: output/hh_analysis_dataset.dta
        crossedBinEpi: output/hhsThatCrossedBinaryEpidemicPeriod.dta
        post1stJuly: output/hh_analysis_dataset_post1stJuly.dta
      moderately_sensitive:
        log1: released_outputs/01_hh_cr_create_analysis_dataset.log
        log2: released_outputs/01_hh_cr_create_analysis_dataset_post1stJuly.log
        log3: released_outputs/01_hh_dropping_hhEpidemics_crossing1stJuly.log
        log4: released_outputs/01_hh_finalMerge.log

  output_descriptive:
    run: stata-mp:latest analysis/02_hh_an_caseFreq_descriptive_plots.do
    needs: [prepare_data]
    outputs:
      moderately_sensitive:
        graph1: released_outputs/an_caseFreq_descr_overall_HH_Histogram.svg
        graph2: released_outputs/an_caseFreq_descr_overall_HH_HistogramOverlay.svg
        log1: released_outputs/02_hh_an_caseFreq_descriptive_plots.log
        log2: released_outputs/an_caseDescrTable.txt

        


  generate_model_data:
    run: python:latest python analysis/generate_model_data.py
    needs: [prepare_data]
    outputs:
      moderately_sensitive:
        log: generate_model_data.log
        timeseries: output/case_series.pickle
        agecats: output/age_categories_series.pickle

  run_model_20_1_1:
    run: python:latest python analysis/opensafely_age_hh_th.py --starting-parameter 1 --add-ridge 20.1
    needs: [generate_model_data]
    outputs:
      moderately_sensitive:
        log: opensafely_age_hh_ridge_20_1_and_seed_1.log


  run_model_20_1_3:
    run: python:latest python analysis/opensafely_age_hh_th.py --starting-parameter 3 --add-ridge 20.1
    needs: [generate_model_data]
    outputs:
      moderately_sensitive:
        log: opensafely_age_hh_ridge_20_1_and_seed_3.log


  run_model_20_1_5:
    run: python:latest python analysis/opensafely_age_hh_th.py --starting-parameter 5 --add-ridge 20.1
    needs: [generate_model_data]
    outputs:
      moderately_sensitive:
        log: opensafely_age_hh_ridge_20_1_and_seed_5.log


  run_model_20_1_81:
    run: python:latest python analysis/opensafely_age_hh_th.py --starting-parameter 81 --add-ridge 20.1
    needs: [generate_model_data]
    outputs:
      moderately_sensitive:
        log: opensafely_age_hh_ridge_20_1_and_seed_81.log


  run_model_20_1_83:
    run: python:latest python analysis/opensafely_age_hh_th.py --starting-parameter 83 --add-ridge 20.1
    needs: [generate_model_data]
    outputs:
      moderately_sensitive:
        log: opensafely_age_hh_ridge_20_1_and_seed_83.log


  run_model_20_1_85:
    run: python:latest python analysis/opensafely_age_hh_th.py --starting-parameter 85 --add-ridge 20.1
    needs: [generate_model_data]
    outputs:
      moderately_sensitive:
        log: opensafely_age_hh_ridge_20_1_and_seed_85.log


  run_model_20_1_23:
    run: python:latest python analysis/opensafely_age_hh_th.py --starting-parameter 23 --add-ridge 20.1
    needs: [generate_model_data]
    outputs:
      moderately_sensitive:
        log: opensafely_age_hh_ridge_20_1_and_seed_23.log


  run_model_20_1_37:
    run: python:latest python analysis/opensafely_age_hh_th.py --starting-parameter 37 --add-ridge 20.1
    needs: [generate_model_data]
    outputs:
      moderately_sensitive:
        log: opensafely_age_hh_ridge_20_1_and_seed_37.log


  run_model_20_1_42:
    run: python:latest python analysis/opensafely_age_hh_th.py --starting-parameter 42 --add-ridge 20.1
    needs: [generate_model_data]
    outputs:
      moderately_sensitive:
        log: opensafely_age_hh_ridge_20_1_and_seed_42.log


  run_model_20_1_13:
    run: python:latest python analysis/opensafely_age_hh_th.py --starting-parameter 13 --add-ridge 20.1
    needs: [generate_model_data]
    outputs:
      moderately_sensitive:
        log: opensafely_age_hh_ridge_20_1_and_seed_13.log

  run_all:
    needs:
      [run_model_20_1_1, run_model_20_1_3, run_model_20_1_5, run_model_20_1_81, run_model_20_1_83, run_model_20_1_85, run_model_20_1_23, run_model_20_1_37, run_model_20_1_42, run_model_20_1_13]
    # In order to be valid this action needs to define a run commmand and some
    # output. We don't really care what these are but the below does the trick.
    # In a future release of the platform, this special action won't need to be
    # defined at all.
    run: cohortextractor:latest --version
    outputs:
      moderately_sensitive:
        whatever: project.yaml
