name: Test that the project is runnable

on: [push]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  test_model:
    runs-on: ubuntu-latest
    name: Test the project can run, using dummy data
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install opensafely-cohort-extractor
    - name: Log into GitHub Container Registry
      run: docker login https://ghcr.io -u ${{ github.actor }} --password ${{ secrets.DOCKER_RO_TOKEN }}
    - name: Update codelists
      run: cohortextractor update_codelists
    - name: Check codelists are up to date
      run: '[[ -z $(git status --porcelain codelists) ]] || (echo "Uncommitted changes to codelists detected, aborting" && exit 1)'

    - name: Run the project
      run: cohortextractor --verbose run dummy run_all expectations
